CREATE PROCEDURE SELECT_PRODUCTS

    @PRODUCTS_NAME NVARCHAR(100)
AS
BEGIN

    SELECT 
        PRODUCTS_ID id,
        PRODUCTS_NAME title,
        PRODUCTS_DESCRIPTION longDescription,
        PRODUCTS_WORTH cost,
        PRODUCTS_STOCK unity,
        PRODUCTS_ENABLE,
        CATEGORY_ID,
        PRODUCTS_USER,
        PRODUCT_IMAGE,
        PRODUCTS_LAST_USER,
        PRODUCTS_DATE,
        PRODUCTS_LAST_DATE
    FROM 
        PRODUCTS
    WHERE 
        PRODUCTS_NAME = @PRODUCTS_NAME;
END;
