CREATE PROCEDURE UPDATE_PRODUCTS

    @PRODUCTS_ID INT,                
    @PRODUCTS_NAME NVARCHAR(100) = NULL,    
    @PRODUCTS_DESCRIPTION NVARCHAR(150) = NULL,
    @PRODUCTS_WORTH FLOAT = NULL,            
    @PRODUCTS_STOCK INT = NULL,              
    @PRODUCTS_ENABLE BIT = NULL,
    @PRODUCT_IMAGE NVARCHAR(MAX) = NULL,             
    @CATEGORY_ID INT = NULL,                 
    @PRODUCTS_LAST_USER NVARCHAR(100) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE PRODUCTS
    SET 
        PRODUCTS_NAME = ISNULL(@PRODUCTS_NAME, [PRODUCTS_NAME]),
        PRODUCTS_DESCRIPTION = ISNULL(@PRODUCTS_DESCRIPTION, [PRODUCTS_DESCRIPTION]),
        PRODUCTS_WORTH = ISNULL(@PRODUCTS_WORTH, [PRODUCTS_WORTH]),
        PRODUCTS_STOCK = @PRODUCTS_STOCK,
        PRODUCTS_ENABLE = @PRODUCTS_ENABLE,
        CATEGORY_ID = @CATEGORY_ID,
        PRODUCTS_LAST_USER = @PRODUCTS_LAST_USER,
        PRODUCTS_LAST_DATE = GETDATE()
    WHERE 
        PRODUCTS_ID = @PRODUCTS_ID; 
END;
